#当前流水线所需要的镜像环境
image: node:alpine

#缓存，gitlab流水线会将安装的node包移除，需要设置缓存
cache:
  key: node_modules
  paths:
    - node_modules
    - build

stages:
  - build2deploy
  - deploy

job_1:
  stage: build2deploy
  script:
    - pwd
    - yarn
    - echo '依赖下载完成'
    - npm run build
    - echo '构建完成'
job_2:
  stage: deploy
  script:
    - docker cp  11520d8fd0e5:build/static/* /usr/local/nginx/html/cdnfile/block-static-site
    - echo 'cdn静态资源部署完成'
    - docker cp -r 11520d8fd0e5:build/* /usr/local/nginx/html/block
    - echo 'html页面部署完成'