#当前流水线所需要的镜像环境
image: node:alpine

#缓存，gitlab流水线会将安装的node包移除，需要设置缓存
cache:
  key: node_modules
  paths:
    - node_modules
# 任务阶段，默认的有 .pre 、 build 、 test 、deploy 、.post(执行有先后顺序)
# 也可以自定义阶段，自己定义的阶段，执行顺序是从上往下依次执行
# 例如下面的例子job_2会比jon_1先执行
stages:
  - build2deploy
job_1:
  stage: build2deploy
  script:
    - yarn
    - echo '依赖下载完成'
    - npm run build
    - echo '构建完成'
    - cp -R ./build/static/* /usr/local/nginx/html/cdnfile/block-static-site
    - echo 'cdn静态资源部署完成'
    - cp -r build/* /usr/local/nginx/html/block
    - echo 'html页面部署完成'